name = "mine-action-ai-backend"
main = "./workers/app.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

[env.production.vars]
ENVIRONMENT = "production"

[env.development.vars]
ENVIRONMENT = "development"

# Base de données D1
[[d1_databases]]
binding = "DB"
database_name = "minedec"
database_id = "a73543cf-ba50-4801-b390-508cf599877e"

# Stockage R2
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "minedec"

# Variables d'environnement (utiliser wrangler secret pour les valeurs sensibles)
[vars]
CORS_ORIGINS = "http://localhost:5173,https://your-frontend.workers.dev"
R2_PUBLIC_URL = "https://e8fa8d76479de666118db7977d6a949e.r2.cloudflarestorage.com/minedec"

# Observability
[observability]
enabled = true